/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import degisken.Degiskenler;
import java.rmi.server.ObjID;
import javax.swing.JOptionPane;
import model.Kullanici;
import service.EmailService;

/**
 *
 * @author susa
 */
public class Anasayfa extends javax.swing.JFrame {

    
    
   
    
    /**asd
     * Creates new form Anasayfa
     */
    public Anasayfa() {
        
        initComponents();
        
        
       String fullName = Degiskenler.loginKul.getFullName();
       
        
        
        
       
        try {
            if (this.fullName != null) {
                this.fullName.setText(fullName);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kullanıcı Girişi Yapılamadı" , "HATA", JOptionPane.INFORMATION_MESSAGE );
            System.out.println(e);
        }
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullName = new javax.swing.JLabel();
        btnCik = new javax.swing.JButton();
        UrunEkle = new javax.swing.JButton();
        Satis = new javax.swing.JButton();
        Gelir = new javax.swing.JButton();
        btnUrunGuncelle = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        raporbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(658, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        fullName.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        fullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fullName);
        fullName.setBounds(450, 10, 170, 20);

        btnCik.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnCik.setText("Çıkış");
        btnCik.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikActionPerformed(evt);
            }
        });
        getContentPane().add(btnCik);
        btnCik.setBounds(540, 40, 80, 20);

        UrunEkle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        UrunEkle.setText("Ürün Ekle");
        UrunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrunEkleActionPerformed(evt);
            }
        });
        getContentPane().add(UrunEkle);
        UrunEkle.setBounds(230, 80, 190, 60);

        Satis.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Satis.setText("Satış");
        Satis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatisActionPerformed(evt);
            }
        });
        getContentPane().add(Satis);
        Satis.setBounds(30, 80, 170, 60);

        Gelir.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Gelir.setText("Kategori/Marka Ekleme");
        Gelir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GelirActionPerformed(evt);
            }
        });
        getContentPane().add(Gelir);
        Gelir.setBounds(30, 170, 170, 60);

        btnUrunGuncelle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUrunGuncelle.setText("Ürün Güncelle");
        btnUrunGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrunGuncelleActionPerformed(evt);
            }
        });
        getContentPane().add(btnUrunGuncelle);
        btnUrunGuncelle.setBounds(470, 80, 150, 60);

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setText("Gün Sonu Al");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 170, 150, 60);

        raporbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        raporbtn.setText("Rapor");
        raporbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raporbtnActionPerformed(evt);
            }
        });
        getContentPane().add(raporbtn);
        raporbtn.setBounds(230, 170, 190, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikActionPerformed

        this.dispose();
        this.setVisible(false);
        new Login().setVisible(true);
        
        
    }//GEN-LAST:event_btnCikActionPerformed

    private void UrunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrunEkleActionPerformed
        
        try {
            this.setVisible(false);
            UrunEkleme urunEkle = new UrunEkleme();
            urunEkle.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UrunEkleActionPerformed

    private void SatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatisActionPerformed
        try {
            this.setVisible(false);
            TopluUrunSatis urunSatis = new TopluUrunSatis();
            urunSatis.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SatisActionPerformed

    private void GelirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GelirActionPerformed

        try {
            this.setVisible(false);
            MarkaEkle gelir = new MarkaEkle();
            gelir.setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GelirActionPerformed

    private void btnUrunGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrunGuncelleActionPerformed

    
        try {
            String veri = "1";
            
            this.setVisible(false);
            GuvenliGiris guvenliGiris = new GuvenliGiris(veri);
            guvenliGiris.setVisible(true);
            
            /**
            UrunGuncelle urunGuncelle = new UrunGuncelle();
            urunGuncelle.setVisible(true);
            * **/
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnUrunGuncelleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            EmailService emailService = new EmailService();
            if (emailService.sendDailyReport(Degiskenler.loginKul.getEmail())) {
                JOptionPane.showMessageDialog(null, "Günlük rapor başarıyla gönderildi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Rapor gönderilirken bir hata oluştu!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Rapor gönderilirken bir hata oluştu: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void raporbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporbtnActionPerformed

        try {    
            String veri = "2";
            
            this.setVisible(false);
            GuvenliGiris guvenliGiris = new GuvenliGiris(veri);
            guvenliGiris.setVisible(true);

            /**
            this.setVisible(false);
            Raporlar raporlar = new Raporlar();
            raporlar.setVisible(true);
            * 
            **/
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_raporbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kullanici defaultUser = new Kullanici();
                new Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gelir;
    private javax.swing.JButton Satis;
    private javax.swing.JButton UrunEkle;
    private javax.swing.JButton btnCik;
    private javax.swing.JButton btnUrunGuncelle;
    private javax.swing.JLabel fullName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton raporbtn;
    // End of variables declaration//GEN-END:variables
}
