/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class GuvenliGiris extends javax.swing.JFrame {

    
    private String veri;
    
    
    
    
    /**
     * Creates new form GuvenliGiris
     */
    public GuvenliGiris(String veri) {
        initComponents();
        this.veri = veri;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCik = new javax.swing.JButton();
        BtnGiris = new javax.swing.JButton();
        GuvenliSifre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCik.setText("Çık");
        BtnCik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCikActionPerformed(evt);
            }
        });

        BtnGiris.setText("Giriş");
        BtnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuvenliSifre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(GuvenliSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCik)
                    .addComponent(BtnGiris))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCikActionPerformed
       this.setVisible(false);
        Anasayfa anasayfa = new Anasayfa();
        anasayfa.setVisible(true);    
    }//GEN-LAST:event_BtnCikActionPerformed

    private void BtnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGirisActionPerformed

        String sifreGuvenlik = "emine123";

        try {
            
            
            if(GuvenliSifre.getText().equals(sifreGuvenlik)){
                
                if(veri.equals("1")){
                    this.setVisible(false);
                    UrunGuncelle urunGuncelle = new UrunGuncelle();
                    urunGuncelle.setVisible(true);
                    
                }
                else if(veri.equals("2")){
                    this.setVisible(false);
                    
                    Raporlar raporlar = new Raporlar();
                    raporlar.setVisible(true);
                    
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Yanlış Güvenlik Parolası");
                }
                
                
            
            }else{
                JOptionPane.showMessageDialog(null, "Yanlış Güvenlik Parolası");
            }
               
            
        } catch (Exception e) {
       
           e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_BtnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCik;
    private javax.swing.JButton BtnGiris;
    private javax.swing.JTextField GuvenliSifre;
    // End of variables declaration//GEN-END:variables
}
